### ISSUE TITLE
Convert to using FastGaussQuadrature.jl

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#15] opened 2018-07-17 17:08 UTC
See https://github.com/ajt60gaibb/FastGaussQuadrature.jl

The idea is to remove the QuantEcon dependency when possible (and when the underlying tests are passing).

https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl has some of the algebra completed, which you can copy.  The key ones to replace in QuantEcon are:
- Beta distribution using `Jacobi` polynomials https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl#L20
- Normal distribution using Gauss-hermite https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl#L41
- Gamma distribution using Gauss-Laguerre: https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl#L34
- Lognormal using normal (and then taking exponentials), though I think you might want to check 
- Exponential distributions using Gauss-Laguerre:  https://github.com/pkofod/DistQuads.jl/blob/master/src/DistQuads.jl#L27
- For General bounded, I don't think that DistQuads does it, but you can use https://github.com/ajt60gaibb/FastGaussQuadrature.jl#the-algorithm-for-gauss-legendre and then just do the transformation for the domain

**Comment by arnavs** [comment] 2018-07-18 02:21
@sglyon This is a roadmap of where we are heading with the quadrature rules.

**Comment by arnavs** [comment] 2018-07-18 19:30
Checklist for myself re distribution implementation: 

- [x] Beta 
- [x] Normal 
- [x] Gamma 
- [x] LogNormal 
- [x] Exponential 
- [x] General on compact support

**Comment by arnavs** [comment] 2018-07-18 20:42
@jlperla This is done now. All QuantEcon dependencies are eliminated, and all regression tests pass. The next step, I think, is to get a more accurate test suite by eliminating our Monte Carlo LLN tests. Those tests are terrible (side note) because they lead to nondeterministic results.

I'll close this issue now

**Closed as completed by arnavs** 2018-07-18 20:42 UTC
Labels: long-term
